name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "."
        target: "/home/${{ secrets.USERNAME }}/tetris"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd tetris/
          python3 -m venv venv
          source venv/bin/activate
          pip install wheel
          pip install Flask gunicorn
          ./insert_release_date.sh
          search="http:\/\/localhost:5000"
          replace="https:\/\/server.pet-projets.ru"
          sed -i "s/$search/$replace/" game.js

          search="database.json"
          replace="..\/database.json"
          sed -i "s/$search/$replace/" server.py

          sudo systemctl restart server
